name = "SQL"
grammar = "sql"
path_suffixes = ["sql"]
line_comments = ["- "]
autoclose_before = "}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = true },
]
prettier_parser_name = "sql"
