name = "PostgreSQL"
grammar = "sql"
pathSuffixes = ["sql"]
lineComments = ["-- "]
autoCloseBefore = ";:,=}])>` \n\t\"'"
brackets = [
    { start = "BEGIN", end = "END;", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = false },
]
